#pragma once

#include <scorum/chain/data_service_factory_def.hpp>

// clang-format off
DATA_SERVICE_FACTORY_DECLARE(
        (account)
        (account_blogging_statistic)
        (account_registration_bonus)
        (atomicswap)
        (fund_budget)
        (post_budget)
        (banner_budget)
        (comment)
        (comment_statistic_scr)
        (comment_statistic_sp)
        (comment_vote)
        (decline_voting_rights_request)
        (dynamic_global_property)
        (hardfork_property)
        (escrow)
        (proposal)
        (proposal_executor)
        (registration_committee)
        (development_committee)
        (registration_pool)
        (content_reward_fund_scr)
        (content_reward_fund_sp)
        (content_fifa_world_cup_2018_bounty_reward_fund)
        (content_reward_scr)
        (voters_reward_scr)
        (voters_reward_sp)
        (scorumpower_delegation)
        (withdraw_scorumpower_route)
        (withdraw_scorumpower_route_statistic)
        (withdraw_scorumpower)
        (witness)
        (witness_schedule)
        (witness_vote)
        (dev_pool)
        (genesis_state)
        (witness_reward_in_sp_migration)
        (blocks_story)
        (adv_moderator)
        )
// clang-format on
